name: Initialize TEI

on: 
  workflow_dispatch:

jobs:
  build_pages:
    name: Publish Edition TEI/XML
    runs-on: ubuntu-latest
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v3
    - name: Install Saxon, Ant and Fundament
      run: |
        apt-get update && apt-get install openjdk-11-jre-headless ant -y --no-install-recommend
        ./shellscripts/dl_saxon.sh
    - name: Install Ant-Contrib
      run: |
        wget https://repo1.maven.org/maven2/ant-contrib/ant-contrib/1.0b3/ant-contrib-1.0b3.jar
        mv ant-contrib-1.0b3.jar /usr/share/ant/lib
    - name: Fetch data
      run: |
        ./shellscripts/fetch_data.sh
        ./shellscripts/fetch_data_legacy.sh
    - name: install python dependecies
      run: |
        pip install -r requirements.txt
    - name: prepare data
      run: |
        python3 ./python/preprocess.py
    - name: Build
      run: |
        ant
    - name: Commit data
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Downloaded/Updated Data
